

export const notificationTypes= Object.freeze({
    SEND_OTP: "SEND_OTP",

    VERIFY_EMAIL: "VERIFY_EMAIL",

    WELCOME_EMAIL: "WELCOME_EMAIL",
    LISTING_CREATED: "LISTING_CREATED",

    BOOKING_CONFIRMED: "BOOKING_CONFIRMED",

    BOOKING_CANCELLED: "BOOKING_CANCELLED",

    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",

    LISTING_UPDATED: "LISTING_UPDATED",

    DELETE_LISTING: "DELETE_LISTING"

});